# ------- Datasource ----------------
spring.datasource.url=jdbc:postgresql://${DOCKER_DB_HOST}:5432/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# ------- Services & Security ----------------
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${AUTH_SERVICE_DOCKER_URL}/api/auth/.well-known/jwks.json
application.config.user-url=${USER_SERVICE_DOCKER_URL}