# ------- Datasource ----------------
spring.datasource.url=jdbc:postgresql://localhost:${DB_HOST_PORT:5432}/${DB_NAME:order_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:11111111}

# ------- Services & Security ----------------
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${AUTH_SERVICE_URL:http://localhost:8080}/api/auth/.well-known/jwks.json
application.config.user-url=${USER_SERVICE_URL:http://localhost:8081}