spring.application.name=orderservice
server.port=${APP_PORT:8082}

# ------- JPA & Hibernate ----------------
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
spring.datasource.driver-class-name=org.postgresql.Driver

# ------- Liquibase ----------------
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true

# ------- Internal API ----------------
internal.api-key=${INTERNAL_API_KEY:default-test-key}