# ------- Datasource ----------------
spring.datasource.url=jdbc:postgresql://localhost:${DB_HOST_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${AUTH_SERVICE_URL:http://localhost:8080}/api/auth/.well-known/jwks.json
application.config.user-url=${USER_SERVICE_URL}